In [7]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

1.11.0


In [8]:
sess = tf.Session()  #creat a instance of a session object from tf.Session class.

## 生成matrix

In [9]:
x = tf.ones([2, 3], tf.int32)  #注意 tf.int32
sess.run(x)    #无论什么tf method, 都得用 sess 来 run

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [10]:
tensor=[[1, 2, 3], [4, 5, 6]] 
x = tf.ones_like(tensor)    #生成形如 tensor 的 identity matrix
sess.run(x)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [11]:
x = tf.fill([2,3],2)   #按照2*3形状 fill 数字2
sess.run(x)

array([[2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [12]:
x = tf.constant(666)  #生成 constant
sess.run(x)

666

In [13]:
x = tf.constant([1,2,3])  
sess.run(x)

array([1, 2, 3], dtype=int32)

In [14]:
x = tf.constant([1,2,3],tf.float32, shape=[3,2])  #constant 变换矩阵形状
#or x = tf.constant([1,2,3], shape=[3,2],dtype = tf.float32)
sess.run(x)

array([[1., 2.],
       [3., 3.],
       [3., 3.]], dtype=float32)

In [15]:
print(sess.run(x))      #显示纯矩阵

[[1. 2.]
 [3. 3.]
 [3. 3.]]


In [16]:
x = tf.random_normal(shape=[1,5],mean=0.0,stddev=1.0,dtype=tf.float32,seed = 1234,name=None)   #生成 randn normal dist
sess.run(x)

array([[ 0.51340485, -0.255814  ,  0.6519913 ,  1.3923638 ,  0.37256798]],
      dtype=float32)

In [17]:
x = tf.random_uniform(shape=[1,5],minval=0, maxval=10,dtype=tf.float32,seed=None,name=None)  #生成随机数
sess.run(x)

array([[8.919983 , 7.104417 , 4.483529 , 5.7645235, 1.3839138]],
      dtype=float32)

In [18]:
x = tf.random_uniform(shape=[1,5],minval=0, maxval=10,dtype=tf.int32,seed=None,name=None)  #需要随机整数改变 dtype 就好
sess.run(x)

array([[2, 0, 4, 5, 8]], dtype=int32)

In [19]:
# help(tf.random_uniform) 查看 tf.random_uniform 帮助

In [20]:
x = tf.linspace(10.0, 12.0, 3, name="linspace")
sess.run(x)

array([10., 11., 12.], dtype=float32)

In [21]:
x = tf.range(start = 0, limit = 10, delta=3, dtype=None, name='range')

with tf.Session() as sess:
      result = sess.run(x)
      print(result)

[0 3 6 9]


## matrix 变换

In [22]:
labels = [[1,2,3],[3,4,5]]

shape = tf.shape(labels)
print(shape)

print(tf.Session().run(tf.shape(labels)))

with tf.Session() as sess:
      result = sess.run(tf.shape(labels))
      print(result)

Tensor("Shape:0", shape=(2,), dtype=int32)
[2 3]
[2 3]


In [23]:

print(tf.Session().run(tf.shape(x)))

[4]


In [24]:
labels = [1,2,3]
print(tf.Session().run(tf.shape(labels)))
print('\n')

x = tf.expand_dims(labels,0)    #升维操作
print(tf.Session().run(x))
print(tf.Session().run(tf.shape(x)))
print('\n')

x = tf.expand_dims(x,0)   #再升一维
print(tf.Session().run(x))
print(tf.Session().run(tf.shape(x)))
print('\n')

x = tf.expand_dims(labels,1)
print(tf.Session().run(x))
print(tf.Session().run(tf.shape(x)))

[3]


[[1 2 3]]
[1 3]


[[[1 2 3]]]
[1 1 3]


[[1]
 [2]
 [3]]
[3 1]


In [25]:
x =  [1, 4]
y =  [2, 5]
z =  [3, 6]
s = tf.stack([x, y, z])   # Pack along first dim.
print(tf.Session().run(s))
print('\n')
s = tf.stack([x, y, z], axis=1) 
print(tf.Session().run(s))

[[1 4]
 [2 5]
 [3 6]]


[[1 2 3]
 [4 5 6]]


In [26]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
s = tf.concat([t1, t2],0)     #体会 stack 和 concat 的不同之处
s1 = tf.stack([t1,t2])
print(tf.Session().run(s))
print('\n')

print(tf.Session().run(s1))
print('\n')
s = tf.concat([t1, t2],1) 
print(tf.Session().run(s))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [27]:
t= [1, 2, 3, 4, 5, 6, 7, 8, 9]
# tensor 't' has shape [9]
print(tf.Session().run(tf.reshape(t, [3, 3])))
print('\n')

t = [[[1, 1], [2, 2]],
    [[3, 3], [4, 4]]]
# tensor 't' has shape [2, 2, 2]
print(tf.Session().run(tf.reshape(t, [2, 4])))
print('\n')


t = [[[1, 1, 1],[2, 2, 2]],[[3, 3, 3],
      [4, 4, 4]],[[5, 5, 5],[6, 6, 6]]]
# tensor 't' has shape [3, 2, 3]


print(tf.Session().run(tf.reshape(t, [-1]))) #pass '[-1]' to flatten 't'
print('\n')

print(tf.Session().run(tf.reshape(t, [2,-1])))
print('\n')

print(tf.Session().run(tf.reshape(t, [-1, 3])))  #按照每行3个 flatten
print('\n')      

print(tf.Session().run(tf.reshape(t, [2, -1, 3]))) #先分两半,再按照每行三个 flatten
print('\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 1 2 2]
 [3 3 4 4]]


[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]


[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]




In [28]:
def sparse_to_dense(sparse_indices,
                    output_shape,
                    sparse_values,
                    default_value=0,
                    validate_indices=True,
                    name=None)  #稀疏矩阵转密集矩阵

SyntaxError: invalid syntax (<ipython-input-28-795a07381c07>, line 6)

In [29]:
a=[[1,2],[3,4],[5,6],[7,8],[9,10]]
a = tf.constant(a)  
x = tf.random_shuffle(a, seed = 10)  #沿着value的第一维进行随机重新排列
print(tf.Session().run(a))
print(tf.Session().run(x))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [ 7  8]]


In [30]:
# a=tf.get_variable(name='a',
#                   shape=[3,4],
#                   dtype=tf.float32,
#                   initializer=tf.random_uniform_initializer(minval=-1,maxval=1))
print(tf.Session().run(x))
print('\n')
b=tf.argmax(input=x,dimension=0)   # 上面 cell 中, x 竖直方向最大值的位置
c=tf.argmax(input=x,dimension=1)   # 上面 cell 中, x 水平方向最大值的位置
d=tf.argmin(input=x,dimension=0)   # 上面 cell 中, x 竖直方向最小值的位置
e=tf.argmin(input=x,dimension=1)   # 上面 cell 中, x 水平方向最小值的位置
print(tf.Session().run(b))
print(tf.Session().run(c))
print(tf.Session().run(d))
print(tf.Session().run(e))

[[ 1  2]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [ 7  8]]


Instructions for updating:
Use the `axis` argument instead
Instructions for updating:
Use the `axis` argument instead
[2 2]
[1 1 1 1 1]
[0 0]
[0 0 0 0 0]


In [31]:
print(tf.Session().run(a))
print(tf.Session().run(x))
print('\n')
print(tf.Session().run(tf.equal(a,x, name=None)))    #比较 a 和 x 每行是否 equal

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [ 7  8]]


[[ True  True]
 [ True  True]
 [False False]
 [False False]
 [False False]]


In [32]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
tf.Session().run(tf.cast(x, tf.int32))    #cast 变换类型

array([1, 2], dtype=int32)

In [33]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(tf.Session().run(a))
print('\n')
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(tf.Session().run(b))
print('\n')
c = tf.matmul(a, b)           # 矩阵乘法 matrix multiplication
print(tf.Session().run(c))    #2*3 matrix * 3*2 matrix = 2*2 matrix

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]


[[ 58  64]
 [139 154]]


In [34]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(tf.Session().run(a))
print('\n')
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[2, 3])
print(tf.Session().run(b))
print('\n')
c = tf.multiply(a, b)           # 矩阵element-wise multiplication乘法, 每个位置相乘
print(tf.Session().run(c))      #2*3 matrix * 2*3 matrix = 2*3 matrix

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[ 7 16 27]
 [40 55 72]]


In [35]:
d = tf.reduce_sum(c,axis=0)    #vertical 方向相加
print(tf.Session().run(d)) 

[47 71 99]


In [36]:
d = tf.reduce_sum(c,axis=1)    ## horizontal 方向相加
print(tf.Session().run(d)) 

[ 50 167]


In [64]:
sess = tf.InteractiveSession()
x = tf.linspace(start=1.0,stop=5.0,num=5,name=None)  # 注意1.0和5.0, 均分区间
y = tf.range(start=1,limit=5,delta=1)
print(sess.run(x))
print(sess.run(y))

[1. 2. 3. 4. 5.]
[1 2 3 4]


## Variables and Placeholders

In [37]:
#placeholder & variable
W = tf.Variable(tf.zeros([784, 10]))   #variable来训练模型时的存储和更新参数w和 b。用于表示算法迭代过程中的中间参数, 需要指定初始值
b = tf.Variable(tf.zeros([10]))

input_data = tf.placeholder(tf.float32, [None, 10])   #placeholder 实例通常用来为算法的input_data作占位符, 不需要指定初始值

In [40]:
c = tf.Variable(3,dtype=tf.float32)
d = tf.placeholder(dtype = tf.float32,shape=None)


#feed_dict is just a dictionary that maps graph elements like variables,constants or placeholders to values. 
#We use it to overwrite the existing values of tensors. 
#We can also use it to change variable values when running them.
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(c,feed_dict = {c:14}))    #overwrite the existing values of tensors.  
print(sess.run(d,feed_dict = {d:[1,1,3,5]}))

14.0
[1. 1. 3. 5.]


## Heron's Formula in TensorFlow

In [62]:
#先定义函数
#再定义placeholder
#再feed data

def compute_area(sides):
  # slice the input to get the sides
  a = sides[:,0]  # 5.0, 2.3
  b = sides[:,1]  # 3.0, 4.1
  c = sides[:,2]  # 7.1, 4.8
  
  # Heron's formula
  s = (a + b + c) * 0.5   # (a + b) is a short-cut to tf.add(a, b)
  areasq = s * (s - a) * (s - b) * (s - c) # (a * b) is a short-cut to tf.multiply(a, b), not tf.matmul(a, b)
  return tf.sqrt(areasq)


with tf.Session() as sess:
  sides = tf.placeholder(tf.float32, shape=(None, 3))  # batchsize number of triangles, 3 sides
  area = compute_area(sides)
  result = sess.run(area, feed_dict = {
      sides: [
        [5.0, 3.0, 7.1],
        [2.3, 4.1, 4.8]
      ]
    })
  print(result)

[6.278497 4.709139]


## Machine Learning using tf.estimator

In [ ]:
import datalab.bigquery as bq
import tensorflow as tf
import pandas as pd
import numpy as np
import shutil

print(tf.__version__)


# In CSV, label is the first column, after the features, followed by the key
CSV_COLUMNS = ['fare_amount', 'pickuplon','pickuplat','dropofflon','dropofflat','passengers', 'key']
FEATURES = CSV_COLUMNS[1:len(CSV_COLUMNS) - 1]
LABEL = CSV_COLUMNS[0]

#生成 pandas df 数据
df_train = pd.read_csv('./taxi-train.csv', header = None, names = CSV_COLUMNS)
df_valid = pd.read_csv('./taxi-valid.csv', header = None, names = CSV_COLUMNS)
df_test = pd.read_csv('./taxi-test.csv', header = None, names = CSV_COLUMNS)

### Train and eval input functions to read from Pandas Dataframe

In [63]:
def make_train_input_fn(df, num_epochs):
  return tf.estimator.inputs.pandas_input_fn(
    x = df,
    y = df[LABEL],
    batch_size = 128,
    num_epochs = num_epochs,
    shuffle = True,
    queue_capacity = 1000
  )


def make_eval_input_fn(df):
  return tf.estimator.inputs.pandas_input_fn(
    x = df,
    y = df[LABEL],
    batch_size = 128,
    shuffle = False,
    queue_capacity = 1000
  )


def make_prediction_input_fn(df):
  return tf.estimator.inputs.pandas_input_fn(
    x = df,
    y = None,              #predition dataset没有 label
    batch_size = 128,
    shuffle = False,
    queue_capacity = 1000
  )

def make_feature_cols()   #告知哪些 columns 是 numeric features, 本例全部只有numeric, create feature columns for estimator
  input_columns = [tf.feature_column.numeric_column(k) for k in FEATURES]
  return input_columns

### Linear Regression with tf.Estimator framework

In [ ]:
tf.logging.set_verbosity(tf.logging.INFO)

OUTDIR = 'taxi_trained'
shutil.rmtree(OUTDIR, ignore_errors = True) # start fresh each time

#Train a linear regression model to predict label value given observation of feature values.
model = tf.estimator.LinearRegressor(
      feature_columns = make_feature_cols(), model_dir = OUTDIR)

model.train(input_fn = make_train_input_fn(df_train, num_epochs = 10))


def print_rmse(model, df):
  metrics = model.evaluate(input_fn = make_eval_input_fn(df))    #检验一下 rmse
  print('RMSE on dataset = {}'.format(np.sqrt(metrics['average_loss'])))
print_rmse(model, df_valid)

predictions = model.predict(input_fn = make_prediction_input_fn(df_test))    #正式计算 prediction
for items in predictions:
  print(items)

### Deep Neural Network regression

In [ ]:
tf.logging.set_verbosity(tf.logging.INFO)
shutil.rmtree(OUTDIR, ignore_errors = True) # start fresh each time

#Train a linear regression model to predict label value given observation of feature values.
model = tf.estimator.DNNRegressor(hidden_units = [32, 8, 2],
      feature_columns = make_feature_cols(), model_dir = OUTDIR)
model.train(input_fn = make_train_input_fn(df_train, num_epochs = 100));

print_rmse(model, df_valid)